/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MediaKeys */

#ifndef _Included_MediaKeys
#define _Included_MediaKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MediaKeys
 * Method:    volumeMute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_commands_MediaKeys_volumeMute
  (JNIEnv *, jclass);

/*
 * Class:     MediaKeys
 * Method:    volumeDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_commands_MediaKeys_volumeDown
  (JNIEnv *, jclass);

/*
 * Class:     MediaKeys
 * Method:    volumeUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_commands_MediaKeys_volumeUp
  (JNIEnv *, jclass);

/*
 * Class:     MediaKeys
 * Method:    songPrevious
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_commands_MediaKeys_songPrevious
  (JNIEnv *, jclass);

/*
 * Class:     MediaKeys
 * Method:    songNext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_commands_MediaKeys_songNext
  (JNIEnv *, jclass);

/*
 * Class:     MediaKeys
 * Method:    songPlayPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_commands_MediaKeys_songPlayPause
  (JNIEnv *, jclass);

/*
 * Class:     MediaKeys
 * Method:    mediaStop
 * Signature: ()V
 */
 /*
JNIEXPORT void JNICALL Java_commands_MediaKeys_mediaStop
  (JNIEnv *, jclass);
*/

#ifdef __cplusplus
}
#endif
#endif
